#!/usr/bin/env bash
# .loop/bin/verify.sh — THE gate. Exit 0 = the change may proceed to a PR.
# Both the builder and the (independent) verifier run this. If it lies, the loop lies.
# Keep it deterministic, ordered fast → slow. Generated by /loop-engineering:init.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

step() { printf '\n=== %s ===\n' "$1"; }

{{VERIFY_STEPS}}

printf '\nVERIFY: PASS\n'
